### ISSUE TITLE
[Recommendation] Enhance translation work

### ISSUE THREAD

**Issue by nelson6e65** [MobSF/docs#16]
Hi!

I used to translate some projects and [Transifex](https://transifex.com) is a tool that I found very useful. That solution is compatible with [Markdown format](https://docs.transifex.com/formats/markdown).

You can set up automation for building translation using GitHub Action or any other CI tool.

> Also, I noticed some of the text in markdown files is not normalized. Tools like [Prettier](https://prettier.io/docs/en/index.html) would be great.

**Comment by ajinabraham** [comment]
Looks like a paid solution, about $120 per/month. 
As an open source project, at this time we cannot use them.

**Comment by nelson6e65** [comment]
It is paid for private projects. For open source project, there is no need to pay.

**Comment by ajinabraham** [comment]
Ah I can see that now, we have done a revamp of the docs site to use Google Translate. It's a hustle to maintain translations.
