### ISSUE TITLE
Update installation guide to get source by downloading zip file

### ISSUE THREAD

**Issue by cdwijayarathna** [MobSF/docs#7]
In the [installation guide](https://mobsf.github.io/docs/#/installation), it says to use git clone to get the MobSF artefacts. When using git clone, it downloads more than 1GB of data. However, for installing the software, only downloading a pack from Github master branch is required, which only downloads 135MB.

Therefore, I suggest to update the installation guide, advising to download MobSF pack by visiting https://github.com/MobSF/Mobile-Security-Framework-MobSF rather than by using git clone.

Furthermore, is it advisable to use the code in the master branch or to use a released version?

**Comment by ajinabraham** [comment]
We use git for tracking updates
https://mobsf.github.io/docs/#/updating
